apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api-gateway
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: api-gateway
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
