apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openshift-console-plugin.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshift-console-plugin.labels" . | nindent 4 }}
data:
  nginx.conf: |
    error_log /dev/stdout info;
    events {}
    http {
      access_log         /dev/stdout;
      include            /etc/nginx/mime.types;
      default_type       application/octet-stream;
      keepalive_timeout  65;

      upstream crowdstrike_us1 {
        server api.crowdstrike.com:443;
      }

      upstream crowdstrike_us2 {
        server api.us-2.crowdstrike.com:443;
      }

      upstream crowdstrike_eu1 {
        server api.eu-1.crowdstrike.com:443;
      }

      # we receive the region in the header thanks to ProxiedFetch, so map that to the right upstream
      map $http_x_cs_region $api_upstream {
        default crowdstrike_us1;
        us-1    crowdstrike_us1;
        us-2    crowdstrike_us2;
        eu-1    crowdstrike_eu1;
      }

      server {
        listen              {{ .Values.plugin.port }} ssl;
        listen              [::]:{{ .Values.plugin.port }} ssl;
        ssl_certificate     /var/cert/tls.crt;
        ssl_certificate_key /var/cert/tls.key;
        root                /usr/share/nginx/html;

        location /crwdapi/ {
          # a rewrite is not usually needed with a location like /foo/ and with a trailing slash on
          # proxy_pass, but variables mess with this behavior https://stackoverflow.com/a/71224059
          rewrite ^/crwdapi/(.*) /$1 break;
          proxy_pass https://$api_upstream;
        }
      }
    }
