name: Container Build
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.devcontainer/**'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.devcontainer/**'
      - '.github/**'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: container build
      run: |
        docker build .
