name: Yarn Lint

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'README.md'
      - '.devcontainer/**'
      - '.github/**'
  pull_request:
    branches: ['main']
    paths-ignore:
      - 'README.md'
      - '.devcontainer/**'
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn lint
