name: Yarn Lint

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.devcontainer/**'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.devcontainer/**'
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint
