name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile
        
      - name: Build
        run: yarn build
